services:
  cards-service:
    image: ghcr.io/g-guandalini/cards-service:latest
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - app-network
  frontend:
    image: ghcr.io/g-guandalini/mtg-price-tracker-web:latest
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - app-network